drop table ReevalRequests
drop table Reviews
drop table RegularMembers
drop table ConferenceParticipants
drop table SpeakersSections
drop table AuthorPapers
drop table ConferenceChairMembers
drop table ChairMembers
drop table ConferenceChosenProgramCommittee
drop table ChosenProgramCommittee
drop table ConferenceAuthors
drop table Conferences
drop table Proposal
drop table Authors
drop table ParticipantSections
drop table Participants
drop table Papers
drop table Sections
drop table Abstracts
drop table SteeringCommittee